author: 'Farshad Mousalou Benis'
author_url: 'https://github.com/farshadmb'
min_acl: internal
module: SternXTask
output: 'Docs/'
swift_version: 5.9
clean: true
skip_undocumented:
xcodebuild_arguments:
  - -workspace
  - SternXTask.xcworkspace
  - -scheme
  - SternXTask
  - CODE_SIGN_IDENTITY=''
exclude:
  - "Pods/**/*"
readme: README.md
