# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  scheme = "SternXTask"
  workspace = "#{scheme}.xcworkspace"
  projectspace = "#{scheme}.xcodeproj"

  before_all do |lane| 
    UI.message "prepare for builds"
    cocoapods()
    UI.message "Checking the xcode requirement version for build or test ..."
    xcversion(version: ">= 15.0")
    UI.message "prepared for build"
  end

 desc "Run App Unit tests"
 lane :runTestCases do |options|

       UI.message "The device raw : #{options[:device]}"
       device =  options[:device]
       UI.message "The device list : #{device}"
       
       clean = false 

       if options[:clean] then 
         clean = options[:clean]
       end

       open_report = false 

       if options[:open_report] then 
         open_report = options[:open_report]
       end

       scan(clean: clean, # clean project folder before test execution
          scheme: scheme,
          workspace: workspace, 
          device: device, # Devices for testing     
          configuration: "Debug",
          code_coverage: true,
          parallel_testing: false, 
          max_concurrent_simulators: 1,
          open_report: open_report)
 end

 lane :GenerateDocument do 
  jazzy(config: ".jazzy.yaml")
 end
 
end
